# memory/summarizer.py
#
# 3-sentence session summary generated by MODEL_SUMMARIZER.

import logging

from shared.llm.openrouter import llm_call_with_retry
from config import settings
from shared.db.client import db

logger = logging.getLogger(__name__)

_SUMMARIZER_SYSTEM = (
    "You summarise a single VARC practice session in exactly 3 sentences. "
    "Sentence 1: what the student practised (mode + skill focus). "
    "Sentence 2: how they did (accuracy and dominant trap). "
    "Sentence 3: one specific thing to work on next time. "
    "No markdown, no filler. Plain prose only."
)


async def generate_session_summary(session_id: str, tg_id: int) -> str:
    session = await db.fetchrow(
        """
        SELECT mode, questions_attempted, questions_correct, skills_practiced
        FROM sessions WHERE session_id = $1::uuid
        """,
        session_id,
    )
    attempts = await db.fetch(
        """
        SELECT a.is_correct, a.trap_fallen_for, q.skill, q.subskill
        FROM attempts a
        LEFT JOIN questions q ON q.question_id = a.question_id
        WHERE a.session_id = $1::uuid
        ORDER BY a.attempted_at ASC
        """,
        session_id,
    )

    if not session:
        return ""

    attempts_count = len(attempts)
    if attempts_count == 0:
        return (
            f"Student opened a {session['mode']} session but did not attempt "
            "any questions. No accuracy data yet. Come back and try one full "
            "question before the session closes."
        )

    correct_count = sum(1 for a in attempts if a['is_correct'])
    accuracy = (correct_count / attempts_count) * 100
    traps = [a['trap_fallen_for'] for a in attempts if a['trap_fallen_for'] and a['trap_fallen_for'] != 'none']
    trap_line = (
        f"most common trap: {max(set(traps), key=traps.count)}"
        if traps else "no repeated trap pattern"
    )

    subskills = [a['subskill'] for a in attempts if a['subskill']]

    user_context = (
        f"Mode: {session['mode']}\n"
        f"Attempts: {attempts_count}\n"
        f"Correct: {correct_count}\n"
        f"Accuracy: {accuracy:.0f}%\n"
        f"Subskills practised: {', '.join(set(subskills)) or 'unknown'}\n"
        f"Traps: {trap_line}"
    )

    try:
        summary = await llm_call_with_retry(
            system=_SUMMARIZER_SYSTEM,
            user=user_context,
            model=settings.MODEL_SUMMARIZER,
        )
        return summary.strip()
    except Exception as e:
        logger.warning(f"summariser failed for {session_id}: {e}")
        return (
            f"{session['mode'].upper()} session: {attempts_count} questions, "
            f"{accuracy:.0f}% accuracy. {trap_line.capitalize()}. "
            "Next session, focus on slowing down on the trap type above."
        )
